# Generated by Django 3.2.3 on 2021-05-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='posts', to='clone.Profile'),
        ),
    ]
