# Generated by Django 3.2.3 on 2021-05-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-post_date']},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='posted',
        ),
    ]
