# Generated by Django 3.2.3 on 2021-05-23 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0007_auto_20210523_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
